### ISSUE TITLE
Still can't connect

### ISSUE THREAD

**Issue by inancgumus** [wojas/docker-mac-network#7]
Hi, thanks for the helpers.

I'm trying to connect to kafka using this docker-compose.yml in this [url](https://github.com/confluentinc/cp-docker-images), the docker-compose.yml I'm using resides in`examples/kafka-single-node` in that repository.

I installed your solution, composed upped it, then, followed your steps, added the vpn config to my tunnelblick. It's OK. Then, when I try to connect to the kafka container, it didn't response.

```bash
# the kafka container uses this port
$ telnet localhost 29092
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host
```

I also tried to expose the port in docker-compose.yml file, still no luck.

This is the docker-compose.yml I'm using to launch kafka and zookeper:

```yaml
---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
    extra_hosts:
      - "moby:127.0.0.1"
```
